name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Deploy to server  
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ 192.168.0.43 }}  
          username: ${{ icr-ASUS-EXPERTCENTER-AIO-E1600WKA-E1600WKA }}  
          key: ${{ ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA6oTxxS+ptBWiCs6JgPI2z3u8dasa5yEcBzeyGskywW baloyimuxe567@gmail.com }}  
          passphrase: ${{ secrets.SSH_PASSPHRASE }}  
          script: |
            cd /opt/lampp/htdoct/will_Capstone
            git pull origin main
            sudo /opt/lampp/lamp restart
